language: php

php:
  - '7.1'
  - '7.2'

addons:
    sonarcloud:
        organization: "assoconnect"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - composer install --no-interaction
    - composer require php-coveralls/php-coveralls
    - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

script:
    - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --log-junit ./tests/logs/phpunit.report.xml
    - php phpcs.phar --standard=PSR12 --ignore=/vendor/* ./
    - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'

after_script:
    - vendor/bin/php-coveralls -v

